### ISSUE TITLE
Alternative Vocabulary report

### ISSUE THREAD

**Issue by olliec** [temyers/cucumber-vocabulary-report#1]
Hi Temyers,

I was exited to see this project but alas it looks to be a skeleton project only. I am looking to generate a step library for a large cuke test repo, do you know of any other plugin that can do this job?

Any help appreciated,
Thanks
Olllie

**Comment by temyers** [comment]
Hi, yeah it was one of my project ideas that I never actually got round to implementing!

[CucumberPro](https://cucumber.io/pro) will have support for this I think
The IntelliJ Cucumber plugin has auto complete support if that helps.

Other than that there's nothing I know off.

Contributions welcome! :)
